#include "DigiKeyboard.h"

void setup() {
  DigiKeyboard.delay(2000); 
  pinMode(1, OUTPUT);
}

void loop() {
  pinMode(0, OUTPUT);
  DigiKeyboard.sendKeyStroke(0); 
  DigiKeyboard.delay(200);


 
 digitalWrite(1, HIGH); 
  delay(20);         
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);
  digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20); digitalWrite(1, HIGH); 
  delay(20);          
  digitalWrite(1, LOW);  
  delay(20);


  DigiKeyboard.print("852000"); 

  while(true); 
}
